name = "lensliar"
type = "javascript"
account_id = "451090b48a9de67d8c1aafc805fc124e"
workers_dev = true
kv_namespaces = [
    { binding = "CONTENT_KV", id = "e7f3a520cf2843b8a6557d8d83e136ce" },
    { binding = "AUTH_KV", id = "ced08099f0d74753ad269b47223f5f34" }
]

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
