name = "lensliar"
main = "src/index.js"
compatibility_date = "2023-10-01"

kv_namespaces = [
    { binding = "CONTENT_KV", id = "3f1b7152df4a403e8c7d2ebbf86df1ea" },
    { binding = "AUTH_KV", id = "7b3ece78720c41c1b084de9e45eddc7a" }
]

[vars]
ADMIN_USERNAME = "default_username"
ADMIN_PASSWORD_HASH = "default_hash"
PEPPER = "default_pepper"
ACCOUNT_ID = "451090b48a9de67d8c1aafc805fc124e"
ALLOWED_ORIGINS = "https://wengguodong.com,https://www.wengguodong.com,https://misakasister.github.io"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
