name = "lensliar"
main = "src/index.js"
compatibility_date = "2025-07-01"

kv_namespaces = [
    { binding = "CONTENT_KV", id = "3f1b7152df4a403e8c7d2ebbf86df1ea" },
    { binding = "AUTH_KV", id = "7b3ece78720c41c1b084de9e45eddc7a"},
    { binding = "IMAGES_KV", id = "06d5b81527944a08ab8f7459bdf17c90"}
]


d1_sql = "8fd2bf88-4ac2-400b-9f78-7bd364dab71d"

# R2存储桶配置（用于存储图片）
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "images"

[vars]
ACCOUNT_ID = "451090b48a9de67d8c1aafc805fc124e"
ALLOWED_ORIGINS = "https://wengguodong.com,https://www.wengguodong.com,https://lensliar.github.io,https://misakasister.github.io"

[observability.logs]
enabled = true
