name: Deploy System

on:
  push:
    branches: [main]

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: ''

      - name: Install worker dependencies
        working-directory: worker
        run: npm install bcryptjs

      - name: Generate password hash
        id: hash_password
        working-directory: worker
        run: |
          export PEPPER="${{ secrets.PEPPER }}"
          export PASSWORD="${{ secrets.ADMIN_PASSWORD }}"
          
          HASH=$(node -e "
            const bcrypt = require('bcryptjs');
            const hash = bcrypt.hashSync(
              process.env.PASSWORD + process.env.PEPPER, 
              10
            );
            console.log(hash);
          ")
          
          echo "HASH_OUTPUT=$HASH" >> $GITHUB_OUTPUT

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Worker
        working-directory: worker
        run: wrangler deploy  # 关键修改：publish → deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD_HASH: ${{ steps.hash_password.outputs.HASH_OUTPUT }}
          PEPPER: ${{ secrets.PEPPER }}

  deploy-pages:
    needs: deploy-worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
